dateModified: 1686665461
elementSources:
  craft\elements\User:
    -
      defaultSort:
        - username
        - asc
      disabled: false
      key: '*'
      tableAttributes:
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      key: admins
      type: native
    -
      heading: 'Account Type'
      type: heading
    -
      key: credentialed
      type: native
    -
      key: inactive
      type: native
email:
  fromEmail: seppe.huysegoms@student.howest.be
  fromName: integration4
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1c79b5d7-455e-4e6e-96ff-ed2b9882f24d: latitude # latitude
    2a983d2f-5b08-4712-b777-c73be7e5f1a1: integration4 # integration4
    2f4f1f6d-5f3a-4d3b-8ba0-61ae0da32b3b: Default # Default
    3c84ce92-1a69-4c08-bce9-4faf902e5241: Common # Common
    7a69dc36-fb93-4af9-8cbe-6b30cc3c3fa4: longitude # longitude
    8b10385d-d50b-4c79-b1bb-9bd2cc6d23bf: 'Public Schema' # Public Schema
    59c3f366-b40a-41db-93cb-9f04c11e413d: placeId # placeId
    77f258a6-7d65-40d3-9c55-b31cc72a5b0a: verhaal # verhaal
    2702fca6-f017-40e8-8716-3427116cc428: integration4 # integration4
    ac14579e-dc02-4c7f-8adc-183287eab957: 'Private Schema' # Private Schema
    b52acbb6-6395-4a5a-b0e6-479f27f9de0a: Adres # Adres
    ea523a3f-b258-43fa-908b-41daa832efea: verhalen # verhalen
    eaba7c1b-32b7-4b06-a390-000594be77a6: 'Front-end users' # Front-end users
plugins:
  graphql-authentication:
    edition: standard
    enabled: true
    licenseKey: KIILU6OK2DBTT9AZ0PFJ3APN
    schemaVersion: 1.3.0
    settings:
      accountCooldown: 'Too many log in attempts; please try again shortly'
      accountDeleted: 'Successfully deleted account'
      accountLocked: 'Sorry, your account is currently locked'
      activationEmailSent: 'You will receive an email if it matches an account in our system'
      allowMagicAuthentication: null
      allowRegistration: '1'
      allowedFacebookDomains: null
      allowedGoogleDomains: null
      allowedMicrosoftDomains: null
      allowedTwitterDomains: null
      appleClientId: null
      appleClientSecret: null
      appleRedirectUrl: null
      appleServiceId: null
      appleServiceSecret: null
      assetMutations: null
      assetNotFound: 'We couldn''t find any matching assets'
      assetQueries: null
      emailNotInScope: 'No email in scope'
      entryMutations: null
      entryNotFound: 'We couldn''t find any matching entries'
      entryQueries: null
      facebookAppId: null
      facebookAppSecret: null
      facebookEmailMismatch: 'Email address doesn''t match allowed Facebook domains'
      facebookRedirectUrl: null
      fieldRestrictions: null
      forbiddenField: 'User doesn''t have permission to access requested field(s)'
      forbiddenMutation: 'User doesn''t have permission to perform this mutation'
      googleClientId: null
      googleEmailMismatch: 'Email address doesn''t match allowed Google domains'
      googleTokenIdInvalid: 'Invalid Google Token ID'
      granularSchemas: null
      invalidEmailAddress: 'Invalid email address'
      invalidHeader: 'Invalid Authorization Header'
      invalidJwtSecretKey: 'Invalid JWT Secret Key'
      invalidLogin: 'We couldn''t log you in with the provided details'
      invalidMagicCode: 'Invalid magic code'
      invalidOauthToken: 'Invalid OAuth Token'
      invalidPasswordMatch: 'Passwords do not match'
      invalidPasswordUpdate: 'We couldn''t update the password with the provided details'
      invalidRefreshToken: 'Invalid Refresh Token'
      invalidRequest: 'Cannot validate request'
      invalidSchema: 'No schema has been set for this user group'
      invalidUserUpdate: 'We couldn''t update the user with the provided details'
      jwtExpiration: '30 minutes'
      jwtRefreshExpiration: '3 months'
      jwtSecretKey: DPJ4Te67lko4-BauCY-SaXXKKIP9Jnhj
      magicLinkSent: 'You will receive an email if it matches an account in our system'
      microsoftAppId: null
      microsoftAppSecret: null
      microsoftEmailMismatch: 'Email address doesn''t match allowed Microsoft domains'
      microsoftRedirectUrl: null
      passwordResetRequired: 'Password reset required; please check your email'
      passwordResetSent: 'You will receive an email if it matches an account in our system'
      passwordSaved: 'Successfully saved password'
      passwordUpdated: 'Successfully updated password'
      permissionType: single
      sameSitePolicy: strict
      schemaId: null
      schemaName: 'Private Schema'
      siteId: null
      skipActivatedCheck: ''
      skipSocialActivation: null
      tokenNotFound: 'We couldn''t find any matching tokens'
      twitterApiKey: null
      twitterApiKeySecret: null
      twitterEmailMismatch: 'Email address doesn''t match allowed Twitter domains'
      twitterRedirectUrl: null
      userActivated: 'Successfully activated user'
      userGroup: '1'
      userHasPassword: 'User not password-less'
      userNotActivated: 'Please activate your account'
      userNotFound: 'We couldn''t find any matching users'
      volumeNotFound: 'We couldn''t find any matching volumes'
system:
  edition: pro
  live: true
  name: integration4
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
