columnSuffix: wfaglscq
contentColumnType: integer(10)
fieldGroup: 3c84ce92-1a69-4c08-bce9-4faf902e5241 # Common
handle: latitude
instructions: null
name: latitude
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
