columnSuffix: bggofaho
contentColumnType: 'decimal(30,20)'
fieldGroup: 3c84ce92-1a69-4c08-bce9-4faf902e5241 # Common
handle: longitude
instructions: null
name: longitude
searchable: false
settings:
  decimals: 20
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
